version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/wemakers
permissions:
  - object: /home/ubuntu/wemakers
    owner: ubuntu
    group: ubuntu
    mode: 700

hooks:
  ApplicationStart:
    - location: /deploy.sh
      timeout: 120
      runas: ubuntu
